### ISSUE TITLE
packet time accuracy

### ISSUE THREAD

**Issue by djeastonca** [iris-edu/miniSEED3#13]
The FDSN object in the Extra Headers section has the _FDSN.Time.Quality_ property which is carried forward from SEED 2.4 Blockette 1001, field 3. In the original specification it is defined as "...a vendor specific value from 0 to 100% of maximum accuracy, taking into account both clock quality and data flags". There is also the _FDSN.Time.MaxEstimatedError_ property defined in the JSON schema. The latter is arguably more useful and does not require itself to be supplemented by manufacturer-specific documentation to interpret it. Propose that _FDSN.Time.Quality_ be dropped for the record, but I recognize that this likely will not be successful due to compatibility concerns with 2.4.

**Comment by chad-earthscope** [comment]
As you acknowledge, some folks, including myself, will prefer to retain the _FDSN.Time.Quality_ header in order to retain the values in earlier miniSEED data.

For what it's worth the _FDSN.Time.MaxEstimatedError_ header was intended to be a more useful (to data users) and manufacturer-agnostic replacement of that header.  When it was initially included there was some doubt from manufacturers that it would be usefully possible to generate such values.  If it could be useful I would be in favor of adding description to _FDSN.Time.Quality_ that recommends using _FDSN.Time.MaxEstimatedError_ whenever possible.  The review group could go all the way to marking _FDSN.Time.Quality_ as deprecated.

**Comment by crotwell** [comment]
The lossless conversion of mseed2 to mseed3 seems a pretty important selling point to me, so I would not want to give that up.

**Comment by djeastonca** [comment]
Thanks for the feedback. I'm happy to hear that _FDSN.TIme.MaxEstimatedError_ is also seen as being more useful. Taking action on the documentation side to discourage the use of the _FDSN.Time.Quality_ property in favour of _FDSN.Time.MaxEstimatedError_ should indeed thereore be considered.

**Comment by djeastonca** [comment]
Wording change merged in 4b43683e816ef07cc0449bb203a70468178e8a57
