### ISSUE TITLE
URI syntax

### ISSUE THREAD

**Issue by djeastonca** [iris-edu/miniSEED3#15]
The syntax in [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) specifies that the forward slash ("/") be used as the delimiter between the hierarchical path components and the underscore ("\_") is explicitly defined as an unreserved character. Using the forward slash is the conventional and familiar way of delimiting path components in a hierarchical namespace and is well supported by existing software used for parsing URIs. It would be ideal to (re)surface the rationale for using underscore "\_" instead.

**Comment by crotwell** [comment]
Regardless of whether or not the underscore was the correct choice of delimiter, the source identifier is defined by a separate specification and is already FDSN approved. So I think it is outside of the mseed3 review team's purview.

That said, documenting the why behind the choice is not a bad idea. My memory of the reasons for choosing underscore instead of slash are hazy. But one argument I think was that while the hierarchical view of the network station channel path is technically correct, channel name's often are used within filenames, and so there is an advantage to not using a delimiter that is meaningful to the shell. 

SourceId specification is here:
http://docs.fdsn.org/projects/source-identifiers/en/v1.0/

**Comment by djeastonca** [comment]
Ahh right - I had forgotten that was already covered under a different specification. @crotwell since this issue is indeed technically outside the scope of mseed3, would there be a more appropriate place elsewhere to capture the rationale for that design decision if the information can be resurrected?

**Comment by crotwell** [comment]
I think opening an issue on the sourceId spec github would be the best starting place. Referencing this issue would help future digital archeologists to find it.

https://github.com/FDSN/source-identifiers/

**Comment by djeastonca** [comment]
Perfect, will do - thanks for the link
