### ISSUE TITLE
Proposal: move the CRC and number of samples from the header section to a 8 bytes footer section *after* the data payload

### ISSUE THREAD

**Issue by kaestli** [iris-edu/miniSEED3#8]
reasoning: 
When writing a record, the CRC, and (depending on the record sizing paradigm) the number of samples become available only after all data of the record is collected. 
Now, miniseed3 format is used for both data transfer and data storage.
In many cases of data transfer, small incremental transfer is an asset (regular data flow, small latency in real-time applications)
In many cases of data storage, larger records are an asset: less overhead due to repetitive header information, more efficient seek processes in larger (e.g. day-) files.
With the proposed change, a miniseed producer can write a header (including intended payload size) and start an incremental transfer of the data before the CRC (and, in case of compressed data, the number of samples fitting into the payload) is known. A miniseed receiver/processor can decide whether to
- whether to start interpretation right away from the receiving the first junk of the record (with the typically small risk of the need to discard results lateron, if the CRC turns out to be invalid) -> in this case, transfer latency is minimized without resulting in inefficient target side storage or the need to record size transcoding
- or to wait for the entire record to be transferred (without relevant advantages or drawbacks compared to classical miniseed2 handling.

Note that
- as many data transfers are using TCP protocols (implementing its own checksums on IP packet level), the CRC is much more a tool for sanity check of storage than of transfer these days
- Moving CRC and number of samples to the end of the record does not imply any overhead in accessing this information, as its position is known from the beginning (header size, plus values of header fields 10, 11, and 12)

**Comment by crotwell** [comment]
The design decision for miniseed3 was explicitly **not** to consider low latency data transmission as a valid use case. Low latency data transmission is a very specialized and complex operation, and probably is better served by a special purpose over the wire protocol. Hence, I think partial data record  transfer should be discouraged in miniseed3 and the added complexity of a crc footer is not worth the benefits.

It may be useful to explore the creation of a low latency over the wire protocol that was loosely based on concepts from miniseed3, but that proposal should probably be submitted separately to WG III.

**Comment by raciner** [comment]
Miniseed3 would be perfectly suitable for low latency data transmission if just the CRC field were moved to the end of the record. This doesn't need a major change of the overall architecture and is very easy to implement in already existing software.

I'm referring to this definition of the miniseed3 header: https://miniseed3.readthedocs.io/en/latest/definition.html

The following would change (fields in the description are numbered as is in the current definition, although they would probably be renumbered and move up by one should the proposal be adopted): 
- Field 8 would be moved to the end of the record. The header would then by 36 + field 10 + field 11 bytes long, 
- All fields behind field 8 would move up by four bytes.
- Data payload would start at 36 + field 10 + field 11
- The CRC (currently field 8) would be at 36 + field 10 + field 11 + field 12

As is obvious, all of the current functionality of the proposed standard would be preserved, also, it would not add any complexity. The main difference is, that the protocol can be used for traditional applications as well as early warning. This will make it more likely that the standard will be supported by manufacturers, any kind of software, be it commercial or free and removes the need for ugly hacks using padding, as people are doing it now. Having a larger user base instead of two competing standards with split user bases which almost do the same would be beneficial for the community, as probably nobody has the resources to develop everything for two different standards.

**Comment by crotwell** [comment]
I understand the changes you are proposing to the record, what I do not understand is how it would be used in practice. To take a simple example, suppose we have a data logger at a station with 3 "early warning" channels, say HHZ, HHN and HHE along with say a dozen other seismic and state of health channels. All of these need to be sent via a socket to the central data center. Can you explain how the sending and receiving systems would use this idea of "partial records" given multiple channels being sent over the same connection?

**Comment by chad-earthscope** [comment]
As has been noted, this proposal still requires the generator of the record to pre-determine the record length.  When compression is used there will very likely be some degree of padding needed to fill out the pre-determined length. 
Alternatively, uncompressed data could be used to avoid padding at the expense of transmission bandwidth.

Neither padded data nor uncompressed data are desirable in long term archives, I would guess most operators would expect to re-pack such records for storage.  A minimal approach might be to create records with compression and apply a specialized process for removing the padding and re-calculating the CRC.  If an operator expects to repackage records for storage, in particular if willing to use transmission bandwidth on uncompressed data, the operator can just as well choose to create time-limited records, e.g. 1-second records, for transmission.

An alternative: specify a special value of the CRC (e.g. 0xFFFFFFFF) used to indicate the CRC is not calculated.  Of course any such value could match an actual CRC computation but the chances are low and it would just mean the record could not be checked.  If we wish to be fancy, we could say that actual CRC values of 0xFFFFFFFF are to be stored as 0, so that CRC checking code would then need to allow 0 == 0xFFFFFFF as a match.  This would be an extremely small reduction (edit: I mean _increase_) of the CRCs collision rate, not sure it's even worth it. 

Edit: it may be better to use 0 as the CRC "unset" value since that is how it set for calculation.  The fancy addition would then be to set actual calculated CRC values of 0 to 0xFFFFFFFF and allow the two to match when checking.

**Comment by raciner** [comment]
@crotwell: We reviewed your comments internally. Any fix we could think of to the problem you mentioned would render the idea useless or overly complicated. In conclusion, we withdraw our proposal.

**Comment by chad-earthscope** [comment]
Closed as withdrawn.

**Comment by crotwell** [comment]
I think it is ok to close this issue.

**Comment by djeastonca** [comment]
Yes it appears that, per Roman's update yesterday that ETH feedback on their remaining open issues has been recorded and that they are satisfied with the current draft of the data format, this issue can be closed
